# Generated by Django 4.0.6 on 2022-07-17 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=200)),
                ('created_instance', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
